# docker-compose.yml

version: "3.1"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: js_learnigns
    ports:
      - "5432:5432"
